services:

# ================= Flight Service ========================

# Flight service DB initialization
  flightservice_mysql_init:
    image: registry.redhat.io/rhel9/mysql-84:latest
    container_name: flightservice_mysql_init
    restart: "no"
    env_file:
      - ./.env.mysql.init
    command: >
      sh -ec "
        until mysqladmin ping -h platform_mysql -u root --silent; do sleep 2; done;
        mysql -h platform_mysql -u root < /init/init-flights-db.sql
      "
    depends_on:
      platform_mysql:
        condition: service_healthy
    volumes:
      - ./db:/init:ro
    networks:
      - flight-booking-network

# -----------

# Flight service application
  flight-service:
    image: quay.io/mukeshs1306/voyagevibes-flightservice:latest
    # build:
    #   context: .
    #   dockerfile: src/main/docker/Dockerfile.jvm
    container_name: flight-service
    restart: always
    env_file:
      - ./.env
    ports:
      - "9092:9092"
      - "8082:8082"
    depends_on:
      auth-service:
        condition: service_started
      platform_mysql:
        condition: service_healthy
      flightservice_mysql_init:
        condition: service_completed_successfully
    volumes:
      - ./https-certs:/etc/ssl/localcerts:ro
    networks:
      - flight-booking-network

# ================= Network ========================

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge
