FROM python:3.12-slim
WORKDIR /workspace
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir opentelemetry-distro opentelemetry-exporter-otlp \
    && opentelemetry-bootstrap --action=install
COPY app ./app
EXPOSE 8085
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8085"]
