FROM registry.redhat.io/ubi9/nginx-126:9.7

# Copy the current Vite build output from the image build context.
COPY --chown=1001:0 dist/. /opt/app-root/src/

# Load logging and HTTPS server config at nginx http context.
COPY --chown=1001:0 ./docker/nginx/01-logging.conf /opt/app-root/etc/nginx.d/01-logging.conf
COPY --chown=1001:0 ./docker/nginx/02-customer-ui-https.conf /opt/app-root/etc/nginx.d/02-customer-ui-https.conf

RUN mkdir -p /opt/app-root/src/logs/nginx && chown -R 1001:0 /opt/app-root/src/logs/nginx

EXPOSE 8080 8443

CMD ["nginx", "-g", "daemon off;"]
