services:
  corp-ui:
    build:
      context: .
      dockerfile: ./docker/Containerfile
    container_name: corp-ui
    restart: always
    env_file:
      - ./.env
    ports:
      - "8086:8443"
    volumes:
      - ./https-certs:/etc/nginx/certs:ro
      - nginx_logs:/opt/app-root/src/logs/nginx
    networks:
      - flight-booking-network

networks:
  flight-booking-network:
    external: true
    name: flight-booking-network

volumes:
  nginx_logs:
