# services:

include:

# Databases
  - ./00-infraservices/databases/postgres/postgres-dockercompose.yml
  - ./00-infraservices/databases/garage-object-storage/garage-dockercompose.yml

# Infra services
  - ./00-infraservices/keycloak/keycloak-dockercompose.yml

# Message brokers
  - ./00-infraservices/message-brokers/kafka-kraft/kafka-dockercompose.yml

# Gateway
  - ./00-infraservices/gateway/kong/kong-dockercompose.yml

# Observability services
  # - ./00-infraservices/observability/prometheus/prometheus-dockercompose.yml
  # - ./00-infraservices/observability/loki/loki-dockercompose.yml
  # - ./00-infraservices/observability/tempo/tempo-dockercompose.yml
  # - ./00-infraservices/observability/grafana/grafana-dockercompose.yml
  - ./00-infraservices/observability/otel/otel-dockercompose.yml

# Authservice
  - ./01-authservice/authservice-dockercompose.yml

# Voyage Vibes UI
  - ./voyagevibes/voyagevibes-ui-dockercompose.yml
