# services:

include:

# Databases
  - ./00-infraservices/databases-docker-compose.yml
  - ./00-infraservices/garage-objectstore-docker-compose.yml

# Infra services
  - ./00-infraservices/kafka-docker-compose.yml
  - ./00-infraservices/kong-gateway-docker-compose.yml
  - ./00-infraservices/keycloak-docker-compose.yml
