services:

# ================= Auth Service ========================

# Auth service DB initialization
  authservice_postgres_init:
    image: registry.redhat.io/rhel9/postgresql-16:latest
    container_name: authservice_postgres_init
    restart: "no"
    env_file:
      - ./.env.postgres.init
    command: >
      sh -ec "
        until pg_isready -h platform_postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE; do sleep 2; done;
        psql -h platform_postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE -v ON_ERROR_STOP=1 -f /init/init-auth-db.sql
      "
    depends_on:
      platform_postgres:
        condition: service_healthy

    volumes:
      - ./db:/init:ro
    networks:
      - flight-booking-network

# ----------

# Auth service
  auth-service:
    image: quay.io/mukeshs1306/voyagevibes-authservice:latest
    # build: 
    #   context: .
    #   dockerfile: ./docker/Containerfile.multistage
    container_name: auth-service
    restart: always
    env_file:
      - ./.env.authservice
    depends_on:
      keycloak:
        condition: service_healthy
      platform_postgres:
        condition: service_healthy
      authservice_postgres_init:
        condition: service_completed_successfully
  
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - ./https-certs/authservice:/etc/ssl/https-certs:ro
    networks:
      - flight-booking-network

# ================= Network ========================

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge
