services:

# =============== Keycloak - Postgres Init ===========================

  keycloak-postgres-init:
    image: registry.redhat.io/rhel9/postgresql-16:latest
    container_name: keycloak-postgres-init
    restart: "no"
    env_file:
      - ./.env
    command: >
      sh -ec "
        until pg_isready -h platform-postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE; do sleep 2; done;
        psql -h platform-postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE  -v ON_ERROR_STOP=1 -f /init/keycloak-init.sql
      "
    depends_on:
      platform-postgres:
        condition: service_healthy
    volumes:
      - ./init-db:/init:ro,Z
    networks:
      - flight-booking-network

# =============== Keycloak ===========================

  keycloak:
    container_name: keycloak
    hostname: keycloak.voyagevibes.in
    image: registry.redhat.io/rhbk/keycloak-rhel9:26.2-15
    restart: always
    env_file:
      - ./.env
    ports:
      - "8091:8091"
    command:
      - start
      - --import-realm
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8091"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 60s
    depends_on:
      platform-postgres:
        condition: service_healthy
      keycloak-postgres-init:
        condition: service_completed_successfully
    volumes:
      - ./realms:/opt/keycloak/data/import:ro,Z
      - ./ssl-certs:/opt/keycloak/certs:ro,Z
    networks:
      flight-booking-network:
        aliases:
          - keycloak.voyagevibes.in

# ================= Network ========================

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge
