services:
  customer-ui:
    image: quay.io/mukeshs1306/voyagevibes-ui-customer:latest
    # build:
    #   context: .
    #   dockerfile: ./docker/Containerfile
    container_name: customer-ui
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8443"
    volumes:
      - ./https-certs:/etc/nginx/certs:ro
      - nginx_logs:/opt/app-root/src/logs/nginx
    networks:
      - flight-booking-network

networks:
  flight-booking-network:
    external: true
    name: flight-booking-network

volumes:
  nginx_logs:
