package com.cloudxplorer.authservice.api;

import com.cloudxplorer.authservice.api.dto.publicauth.AuthSessionResponse;
import com.cloudxplorer.authservice.api.dto.publicauth.OtpChallengeResponse;
import com.cloudxplorer.authservice.api.dto.publicauth.OtpRequest;
import com.cloudxplorer.authservice.api.dto.publicauth.OtpVerifyRequest;
import com.cloudxplorer.authservice.api.dto.publicauth.PublicGoogleStartResponse;
import com.cloudxplorer.authservice.api.dto.publicauth.StepUpVerifyResponse;
import com.cloudxplorer.authservice.api.dto.session.LogoutRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestParam;

@Tag(name = "Public Auth", description = "Public customer authentication and step-up verification endpoints.")
public interface PublicAuthApi {
    @Operation(
        summary = "Start Google login",
        description = "Builds the Google broker authorization URL, state, PKCE challenge method, and code verifier for the public login flow."
    )
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "Google login flow initialized",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = PublicGoogleStartResponse.class),
                examples = @ExampleObject(value = OpenApiExamples.PUBLIC_GOOGLE_START_RESPONSE)
            )
        )
    })
    @GetMapping("/api/v1/auth/public/google/start")
    ResponseEntity<PublicGoogleStartResponse> startGoogleLogin();

    @Operation(
        summary = "Complete Google login callback",
        description = "Exchanges the Google authorization code, validates state/code verifier, and issues an application session."
    )
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "Public login completed",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = AuthSessionResponse.class),
                examples = @ExampleObject(value = OpenApiExamples.AUTH_SESSION_RESPONSE)
            )
        )
    })
    @GetMapping("/api/v1/auth/public/google/callback")
    ResponseEntity<AuthSessionResponse> googleCallback(
        @Parameter(
            in = ParameterIn.QUERY,
            description = "Authorization code returned by Google or Keycloak.",
            example = "4/0Adqt8qj72hf98",
            required = true
        )
        @RequestParam("code") String code,
        @Parameter(
            in = ParameterIn.QUERY,
            description = "State value generated by the start endpoint.",
            example = "9e9fd994-2e5b-4524-b360-a8ae99489c4f",
            required = true
        )
        @RequestParam("state") String state,
        @Parameter(
            in = ParameterIn.HEADER,
            description = "Fallback PKCE code verifier if the caller stores it client-side.",
            example = "f365f4f0c32644a6a8ac90196dc2a54d7b7a06e6a8054278a6bf0e7f497d2b49"
        )
        @RequestHeader(value = "X-Code-Verifier", required = false) String codeVerifier,
        @Parameter(
            in = ParameterIn.HEADER,
            description = "Optional device label recorded against the created session.",
            example = "Chrome on Windows"
        )
        @RequestHeader(value = "X-Device", required = false) String device,
        @Parameter(
            in = ParameterIn.HEADER,
            description = "Optional caller IP address used for session telemetry.",
            example = "10.10.20.31"
        )
        @RequestHeader(value = "X-Forwarded-For", required = false) String ip
    );

    @Operation(
        summary = "Logout public user",
        description = "Logs out the current public user by revoking the refresh token and optionally revoking all sessions."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
        required = true,
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = LogoutRequest.class),
            examples = @ExampleObject(value = OpenApiExamples.LOGOUT_REQUEST)
        )
    )
    @ApiResponses(value = {
        @ApiResponse(responseCode = "204", description = "Public session revoked")
    })
    @PostMapping("/api/v1/auth/public/logout")
    ResponseEntity<Void> publicLogout(
        @Parameter(
            in = ParameterIn.HEADER,
            description = "Current user identifier resolved by the authservice.",
            example = "user-public-1001"
        )
        @RequestHeader(value = "X-User-Id", required = false) String userId,
        @Valid @RequestBody LogoutRequest request
    );

    @Operation(
        summary = "Request public step-up OTP",
        description = "Creates an OTP challenge for a sensitive public-user action such as payments or profile changes."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
        required = true,
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = OtpRequest.class),
            examples = @ExampleObject(value = OpenApiExamples.OTP_REQUEST)
        )
    )
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "OTP challenge created",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = OtpChallengeResponse.class),
                examples = @ExampleObject(value = OpenApiExamples.OTP_CHALLENGE_RESPONSE)
            )
        )
    })
    @PostMapping("/api/v1/auth/public/step-up/otp/request")
    ResponseEntity<OtpChallengeResponse> requestStepUpOtp(@Valid @RequestBody OtpRequest request);

    @Operation(
        summary = "Verify public step-up OTP",
        description = "Validates a previously-issued OTP challenge and returns the step-up verification window."
    )
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
        required = true,
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(implementation = OtpVerifyRequest.class),
            examples = @ExampleObject(value = OpenApiExamples.OTP_VERIFY_REQUEST)
        )
    )
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "OTP verified",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = StepUpVerifyResponse.class),
                examples = @ExampleObject(value = OpenApiExamples.STEP_UP_VERIFY_RESPONSE)
            )
        )
    })
    @PostMapping("/api/v1/auth/public/step-up/otp/verify")
    ResponseEntity<StepUpVerifyResponse> verifyStepUpOtp(@Valid @RequestBody OtpVerifyRequest request);

    final class OpenApiExamples {

        private OpenApiExamples() {
        }

        public static final String HEALTH_RESPONSE = """
            {
              "status": "UP",
              "timestamp": "2026-04-06T10:15:30Z",
              "environment": "dev",
              "details": {
                "mode": "readiness",
                "keycloak.status": "UP",
                "keycloak.reason": "OK",
                "db.status": "UP",
                "db.reason": "OK",
                "db.target": "jdbc:postgresql://localhost:5432/authdb",
                "hostname": "localhost",
                "appBaseUrl": "https://localhost:9091",
                "environment": "dev"
              }
            }
            """;

        public static final String PUBLIC_GOOGLE_START_RESPONSE = """
            {
              "authorizationUrl": "http://localhost:8090/realms/voyagevibes-public/protocol/openid-connect/auth?client_id=voyagevibes-public-web&redirect_uri=https://customer-ui.voyagevibes.in:8080/auth/google/callback&response_type=code&scope=openid%20email%20profile&prompt=select_account&state=9e9fd994-2e5b-4524-b360-a8ae99489c4f&code_challenge=0SczqQ4n2FRB0d5p74xQ8Ybp4VhP6VYqghG2aX_aVgQ&code_challenge_method=S256&kc_idp_hint=google",
              "state": "9e9fd994-2e5b-4524-b360-a8ae99489c4f",
              "codeChallengeMethod": "S256",
              "codeVerifier": "f365f4f0c32644a6a8ac90196dc2a54d7b7a06e6a8054278a6bf0e7f497d2b49"
            }
            """;

        public static final String AUTH_SESSION_RESPONSE = """
            {
              "tokens": {
                "accessToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.public-access-token",
                "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.public-refresh-token",
                "expiresIn": 600
              },
              "user": {
                "userId": "user-public-1001",
                "email": "customer@example.com",
                "realm": "PUBLIC",
                "status": "ACTIVE",
                "roles": [
                  "CUSTOMER"
                ]
              },
              "isNewUser": false,
              "profileStatus": "COMPLETE",
              "mfaLevel": "LOW"
            }
            """;

        public static final String OTP_REQUEST = """
            {
              "purpose": "BOOKING_PAYMENT",
              "channel": "EMAIL",
              "emailOrPhone": "customer@example.com"
            }
            """;

        public static final String OTP_CHALLENGE_RESPONSE = """
            {
              "challengeId": "otp-9af7ee8a-c267-4b95-af31-f5d65baf4f1b",
              "expiresIn": 300,
              "resendAfter": 30
            }
            """;

        public static final String OTP_VERIFY_REQUEST = """
            {
              "challengeId": "otp-9af7ee8a-c267-4b95-af31-f5d65baf4f1b",
              "otp": "482911"
            }
            """;

        public static final String STEP_UP_VERIFY_RESPONSE = """
            {
              "verified": true,
              "expiresAt": "2026-04-06T10:25:30Z"
            }
            """;

        public static final String CORP_LOGIN_INIT_REQUEST = """
            {
              "email": "ops.agent@voyagevibes.in",
              "deviceInfo": {
                "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
                "ip": "10.10.20.31",
                "deviceId": "corp-device-01",
                "platform": "Windows"
              }
            }
            """;

        public static final String CORP_LOGIN_INIT_RESPONSE = """
            {
              "loginFlowId": "corp-79f0b89f-8ff9-41b0-b5eb-20d64ec0c532",
              "allowedFactors": [
                "PASSWORD"
              ],
              "requiresStepUp": false
            }
            """;

        public static final String CORP_LOGIN_VERIFY_REQUEST = """
            {
              "loginFlowId": "corp-79f0b89f-8ff9-41b0-b5eb-20d64ec0c532",
              "factorType": "PASSWORD",
              "assertion": "TempPassword!123"
            }
            """;

        public static final String CORP_LOGIN_VERIFY_RESPONSE = """
            {
              "session": {
                "tokens": {
                  "accessToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.corp-access-token",
                  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.corp-refresh-token",
                  "expiresIn": 600
                },
                "user": {
                  "userId": "corp-user-2001",
                  "email": "ops.agent@voyagevibes.in",
                  "realm": "CORP",
                  "status": "ACTIVE",
                  "roles": [
                    "OPS_AGENT"
                  ]
                },
                "isNewUser": false,
                "profileStatus": "COMPLETE",
                "mfaLevel": "LOW"
              },
              "challengeRequired": false,
              "challengeType": null,
              "challengeMetadata": {}
            }
            """;

        public static final String CORP_MFA_CHALLENGE_REQUEST = """
            {
              "loginFlowId": "corp-79f0b89f-8ff9-41b0-b5eb-20d64ec0c532",
              "factorType": "OTP"
            }
            """;

        public static final String CORP_MFA_CHALLENGE_PASSKEY_REQUEST = """
            {
              "loginFlowId": "corp-79f0b89f-8ff9-41b0-b5eb-20d64ec0c532",
              "factorType": "PASSKEY"
            }
            """;

        public static final String WEBAUTHN_CHALLENGE_RESPONSE = """
            {
              "challenge": "fd46972d-b4c1-4064-9d4d-9ea581aec69c",
              "rpId": "localhost",
              "timeout": 60000
            }
            """;

        public static final String CORP_MFA_VERIFY_REQUEST = """
            {
              "challengeId": "mfa:corp-79f0b89f-8ff9-41b0-b5eb-20d64ec0c532",
              "otpOrAssertion": "482911"
            }
            """;

        public static final String REFRESH_TOKEN_REQUEST = """
            {
              "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.public-refresh-token"
            }
            """;

        public static final String LOGOUT_REQUEST = """
            {
              "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.public-refresh-token",
              "allSessions": true
            }
            """;

        public static final String SESSION_LIST_RESPONSE = """
            {
              "sessions": [
                {
                  "sessionId": "sess-1001",
                  "device": "Chrome on Windows",
                  "ip": "10.10.20.31",
                  "createdAt": "2026-04-06T09:15:30Z",
                  "lastSeenAt": "2026-04-06T10:15:30Z",
                  "riskLevel": "LOW"
                }
              ]
            }
            """;

        public static final String ME_RESPONSE = """
            {
              "userId": "user-public-1001",
              "email": "customer@example.com",
              "firstName": "Sky",
              "lastName": "Fly",
              "mobile": "+919876543210",
              "mobileVerified": true,
              "realm": "PUBLIC",
              "roles": [
                "CUSTOMER"
              ],
              "profileStatus": "COMPLETE"
            }
            """;

        public static final String UPDATE_ME_REQUEST = """
            {
              "firstName": "Sky",
              "lastName": "Traveler",
              "mobile": "+919876543210",
              "preferences": {
                "seatPreference": "WINDOW",
                "mealPreference": "VEG"
              }
            }
            """;

        public static final String CORP_USER_CREATE_REQUEST = """
            {
              "email": "support.agent@voyagevibes.in",
              "roleIds": [
                "SUPPORT_AGENT"
              ],
              "department": "Support",
              "managerId": "corp-admin-001"
            }
            """;

        public static final String CORP_USER_UPDATE_REQUEST = """
            {
              "status": "ACTIVE",
              "department": "Operations",
              "managerId": "corp-admin-001"
            }
            """;

        public static final String ROLE_ASSIGNMENT_REQUEST = """
            {
              "roleId": "FINANCE_AGENT"
            }
            """;
    }
}