services:

# --------- Payment Service ----------

# Payment service DB initialization
  paymentservice_postgres_init:
    image: registry.redhat.io/rhel9/postgresql-16:latest
    container_name: paymentservice_postgres_init
    restart: "no"
    env_file:
      - ./.env.postgres.init
    command: >
      sh -ec "
        until pg_isready -h platform_postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE; do sleep 2; done;
        psql -h platform_postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE -v ON_ERROR_STOP=1 -f /init/init-payment-db.sql
      "
    depends_on:
      platform_postgres:
        condition: service_healthy
    volumes:
      - ./db:/init:ro
    networks:
      - flight-booking-network

# Payment Service API
  payment-service:
    image: quay.io/mukeshs1306/voyagevibes-paymentservice:latest
    # build:
    #   context: .
    #   dockerfile: ./docker/Containerfile
    container_name: payment-service
    restart: always
    env_file:
      - ./.env
    ports:
      - "8085:8085"
      - "9095:9095"
    volumes:
      - ./https-certs:/app/https-certs:ro
    depends_on:
      paymentservice_postgres_init:
        condition: service_completed_successfully
    networks:
      - flight-booking-network

# -------  Network ---------

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge
