FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o /out/notification-service ./cmd/server

FROM docker.io/otel/autoinstrumentation-go:latest AS auto-instrumentation

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/notification-service .
EXPOSE 8086
ENTRYPOINT ["./notification-service"]
