FROM golang:1.23-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o /out/notification-service ./cmd/server

FROM alpine:3.21
WORKDIR /app
COPY --from=build /out/notification-service .
EXPOSE 8086
ENTRYPOINT ["./notification-service"]
