services:

# --------- Booking Service ----------

# MSSQL Initialization Container for Booking Service
  bookingservice_mssql_init:
    image: mcr.microsoft.com/mssql/rhel/server:2025-latest
    container_name: bookingservice_mssql_init
    restart: "no"
    env_file:
      - ./.env.mssql.init
    command: >
      /bin/sh -ec "
        until /opt/mssql-tools18/bin/sqlcmd -S platform_mssql -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" -C; do sleep 2; done;
        /opt/mssql-tools18/bin/sqlcmd -S platform_mssql -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -i /init/init-booking-db.sql
      "
    depends_on:
      platform_mssql:
        condition: service_healthy
    volumes:
      - ./db:/init:ro
    networks:
      - flight-booking-network

# Booking Service API
  booking-service:
    build:
      context: .
      dockerfile: ./docker/Containerfile
    container_name: booking-service
    restart: always
    env_file:
      - ./.env
    ports:
      - "8083:8083"
      - "9093:9093"
    volumes:
      - ./https-certs:/app/https-certs:ro
    depends_on:
      bookingservice_mssql_init:
        condition: service_completed_successfully
      platform_mssql:
        condition: service_healthy
    networks:
      - flight-booking-network

# -------  Network ---------

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge
