FROM registry.redhat.io/ubi9/openjdk-17@sha256:615a2e789a3b2d982ec9e126d525697032440b1eace5dfea4fe6618cc85a7935

WORKDIR /app

ARG PORT=808
ARG JAR_FILE=target/authservice-0.0.1-SNAPSHOT.jar

RUN mkdir -p /app/logs

COPY ${JAR_FILE} app.jar

EXPOSE ${PORT}

ENTRYPOINT ["java", "-jar", "app.jar"]
