services:

# --------- Customer Service ----------

  customerservice_mongodb_init:
    image: quay.io/mongodb/mongodb-community-server
    container_name: customerservice_mongodb_init
    restart: "no"
    env_file:
      - ./.env.mongodb.init
    command: >
      sh -ec "
        until mongosh --host platform_mongodb --username \"$$MONGODB_INITDB_ROOT_USERNAME\" --password \"$$MONGODB_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin --quiet --eval \"db.adminCommand({ ping: 1 })\"; do sleep 2; done;
        mongosh --host platform_mongodb --username \"$$MONGODB_INITDB_ROOT_USERNAME\" --password \"$$MONGODB_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin /init/init-customer-db.js
      "
    depends_on:
      platform_mongodb:
        condition: service_healthy
    volumes:
      - ./db:/init:ro
    networks:
      - flight-booking-network

# Customer Service API
  customer-service:
    image: quay.io/mukeshs1306/voyagevibes-customerservice:latest
    # build:
    #   context: .
    #   dockerfile: ./docker/Containerfile
    container_name: customer-service
    restart: always
    env_file:
      - ./.env
    ports:
      - "8084:8084"
      - "9094:9094"
    volumes:
      - ./https-certs:/opt/app-root/src/https-certs:ro
    depends_on:
      customerservice_mongodb_init:
        condition: service_completed_successfully
      platform_mongodb:
        condition: service_healthy
    networks:
      - flight-booking-network

# -------  Network ---------

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge
