services:
  kafka:
    image: docker.io/apache/kafka:3.8.0  # Or latest; supports KRaft natively
    container_name: kafka-kraft
    ports:
      - "9192:9192"
      - "9193:9093"  # Controller port
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9192
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9192
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'  # Generate with /opt/kafka/bin/kafka-storage.sh random-uuid inside container
    volumes:
      - kafka_data:/tmp/kraft-combined-logs  # Volume kafka_data
    command: >
      sh -c "
        sed -ri 's|^listeners=.*|listeners=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9192|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^advertised.listeners=.*|advertised.listeners=INTERNAL://kafka:9092,EXTERNAL://localhost:9192|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^inter.broker.listener.name=.*|inter.broker.listener.name=INTERNAL|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^controller.listener.names=.*|controller.listener.names=CONTROLLER|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^listener.security.protocol.map=.*|listener.security.protocol.map=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^process.roles=.*|process.roles=broker,controller|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^node.id=.*|node.id=1|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^controller.quorum.voters=.*|controller.quorum.voters=1@kafka:9093|' /opt/kafka/config/kraft/server.properties &&
        sed -ri 's|^log.dirs=.*|log.dirs=/tmp/kraft-combined-logs|' /opt/kafka/config/kraft/server.properties &&
        /opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t MkU3OEVBNTcwNTJENDM2Qk -c /opt/kafka/config/kraft/server.properties &&
        /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      "
    networks:
      - flight-booking-network

# ================= Network ========================

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge

# ================= Volumes ========================

volumes:
  kafka_data:
