services:
  kafka:
    image: docker.io/apache/kafka:3.8.0  # Or latest; supports KRaft natively
    container_name: kafka-kraft
    env_file:
      - ./.env.kafka
    ports:
      - "9192:9192"
      - "9193:9093"  # Controller port
    volumes:
      - kafka_data:/tmp/kraft-combined-logs  # Volume kafka_data
    networks:
      - flight-booking-network

# ================= Network ========================

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge

# ================= Volumes ========================

volumes:
  kafka_data:
