services:

  kong_postgres:
    image: registry.redhat.io/rhel9/postgresql-16:latest
    container_name: kong_postgres
    restart: always
    env_file:
      - ./.env.kong
    volumes:
      - kong_postgres_data:/var/lib/pgsql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - flight-booking-network

# -----------

  kong-migrations:
    image: docker.io/library/kong
    command: >
      /bin/sh -c
      "kong migrations bootstrap --vv ||
      (kong migrations up --vv && kong migrations finish --vv)"
    env_file:
      - ./.env.kong
    volumes:
      - ./https-certs/kong-certs:/etc/kong/certs:ro
    depends_on:
      kong_postgres:
        condition: service_healthy
    networks:
      - flight-booking-network

# -----------

  kong_gateway:
    image: docker.io/library/kong
    container_name: kong_voyagevibes_gateway
    env_file:
      - ./.env.kong
    ports:
      - "8000:8000"  # Proxy (your services entrypoint)
      - "8443:8443"  # HTTPS
      - "8001:8001"  # Admin API
    volumes:
      - ./https-certs/kong-certs:/etc/kong/certs:ro
    depends_on:
      kong_postgres:
        condition: service_healthy
      kong-migrations:
        condition: service_completed_successfully
    networks:
      - flight-booking-network

# ================= Network ========================

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge

# ================= Volumes ========================

volumes:
  kong_postgres_data:
