services:

# --------- Notification Service ----------

  notificationservice_postgres:
    image: registry.redhat.io/rhel9/postgresql-16:latest
    container_name: notificationservice_postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5436:5432"
    volumes:
      - notificationservice_postgres_data:/var/lib/pgsql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - flight-booking-network

  notificationservice_postgres_init:
    image: registry.redhat.io/rhel9/postgresql-16:latest
    container_name: notificationservice_postgres_init
    restart: "no"
    env_file:
      - ./.env
    command: >
      sh -ec "
        until pg_isready -h notificationservice_postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE; do sleep 2; done;
        psql -h notificationservice_postgres -U $$POSTGRESQL_USER -d $$POSTGRESQL_DATABASE -v ON_ERROR_STOP=1 -f /init/init-notification-db.sql
      "
    depends_on:
      notificationservice_postgres:
        condition: service_healthy
    volumes:
      - ./db:/init:ro
    networks:
      - flight-booking-network

  notificationservice_redis:
    image: registry.redhat.io/rhel9/redis-7:9.7
    container_name: notificationservice_redis
    restart: always
    env_file:
      - ./.env
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "$$REDIS_PASSWORD"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - flight-booking-network

  notification-service:
    build:
      context: .
      dockerfile: ./docker/Containerfile
    container_name: notification-service
    restart: always
    env_file:
      - ./.env
    ports:
      - "8087:8087"
    depends_on:
      notificationservice_postgres:
        condition: service_healthy
      notificationservice_postgres_init:
        condition: service_completed_successfully
      notificationservice_redis:
        condition: service_healthy
    networks:
      - flight-booking-network

# -------  Network ---------

networks:
  flight-booking-network:
    name: flight-booking-network
    driver: bridge

# ----------  Volumes --------------

volumes:
  notificationservice_postgres_data:
