FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/FlightService/FlightService.csproj src/FlightService/
RUN dotnet restore src/FlightService/FlightService.csproj
COPY src/FlightService src/FlightService
RUN dotnet publish src/FlightService/FlightService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8083
ENTRYPOINT ["dotnet", "FlightService.dll"]
