apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100        # Loki service URL
    basicAuth: false             # Set to true if Loki requires basic auth
    isDefault: true              # Make this the default data source
    editable: true               # Allow editing in Grafana UI