apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    uid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100        # Loki service URL
    basicAuth: false             # Set to true if Loki requires basic auth
    isDefault: false              # Make this the default data source
    editable: true               # Allow editing in Grafana UI
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    editable: true
    uid: tempo
