FROM registry.redhat.io/ubi9/python-39:9.7

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
COPY app ./app

EXPOSE 8085
CMD ["python", "main.py"]

